descriptions = {
    'CLEAR_DAY',
    'CLEAR_NIGHT',
    'PARTLY_CLOUDY_DAY',
    'PARTLY_CLOUDY_NIGHT',
    'CLOUDY',
    'RAIN',
    'SHOWERS_DAY',
    'SHOWERS_NIGHT',
    'SLEET',
    'RAIN_SNOW',
    'RAIN_SNOW_SHOWERS_DAY',
    'RAIN_SNOW_SHOWERS_NIGHT',
    'SNOW',
    'SNOW_SHOWERS_NIGHT',
    'WIND',
    'FOG',
    'THUNDER',
    'THUNDER_RAIN',
    'THUNDER_SHOWERS_DAY',
    'THUNDER_SHOWERS_NIGHT',
    'HAIL'
}

default_colors = {
    'main': "#111",
    'moon': "#353545",
    'fog': "#CCC",
    'fogbank': "#AAA",
    'light_cloud': "#888",
    'cloud': "#666",
    'dark_cloud': "#444",
    'thunder': "#FF0",
    'snow': "#C2EEFF",
    'hail': "#CCF",
    'sleet': "#C2EEFF",
    'wind': "#777",
    'leaf': "#2C5228",
    'rain': "#7FDBFF",
    'sun': "#FFDC00"
}
